### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Sinogard** [Noaaan/MythicMetals#110]
full log here: https://paste.ee/p/PTV38

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mythicmetals'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_1813.<init>(int, net.minecraft.class_3414, net.minecraft.class_1792$class_1793)'
	at nourl.mythicmetals.item.MythicItems$CustomMusicDiscItem.<init>(MythicItems.java:165)
	at nourl.mythicmetals.tools.MythicTools$Frogery.<clinit>(MythicTools.java:117)
	at nourl.mythicmetals.tools.MythicTools.afterFieldProcessing(MythicTools.java:88)
	at io.wispforest.owo.registration.reflect.FieldRegistrationHandler.processSimple(FieldRegistrationHandler.java:55)
	at nourl.mythicmetals.MythicMetals.onInitialize(MythicMetals.java:59)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 16 more

**Comment by Noaaan** [comment]
You are using a 1.19 ONLY build on 1.19.2. 
Please downgrade to 0.15.4.
